language: scala
scala:
- 2.12.0
jdk:
- oraclejdk8
env:
  global:
  - LIB_VERSION=$TRAVIS_BUILD_NUMBER
  - secure: PwBDpBYi46nigJVYpIhdcvgUgJIBNKaNQH6WoX1vAvJ1S8ruX3gmyaHQM5Dt4LyxO5l4TxSsuVSAnCgT1qqClRW494ympprrojIJ0d/mPbL1PFgjz23W8WPrSA3R3ypGOZBv4iQidkpa2/KOYkslPR+xZS+lqjrCNLHfk7Vew8Y=
  - secure: fnPOJvqDFon/3pc/NQ3jeADjhSCppPdCL8cuUzd1HtstyrvLueaunX9mGPvIh6kTQBaPhhMApDFT0KDONbpWIaTLEgUBWZPsGEIsLNRXq08xoFejc1yPccHfe1aF6Bkr9K9Uwb2HcNQJeAuuBGJGSBgU1ABqAy3af8lxGtfE04M=
  - secure: fiSsiMm2grufn32L9hcl5Z1kgjwV2Q/CeKklTH+UZShYf0J4Mb1Cn2LrEOXycUucWbGM+dfMX5za/o+AJ7xBT596k7rFHFV+Xy/UfdDx0L3zsZrafqa2gMOEq2ubQDvYciGRy9HdQ5m+pZFn+usp78FMQDh0Qc1AKlo/YTLbLME=
before_script: ./publish/bintray.sh
script: sbt test +publishSigned
